Issue #22- [M8]-[Replace this use of System.out or System.err by a logger.]
munterkalmsteiner/inception pull request #25
Opened 2019-10-05 20:07 UTC by katikireddy622

**What's in the PR**

Replaced System.out & System.err with Loggers

2019-10-14 09:39 UTC, munterkalmsteiner requested changes
Looks good, except two issues (see comments).

2019-10-14 09:39 UTC, munterkalmsteiner commented on .sonarcloud.properties
> +
Do not include sonarqube files in the repository.

2019-10-14 09:39 UTC, munterkalmsteiner commented on inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImplQualifierIntegrationTest.java
> +        property.toKBHandle();
This change is not related to logging.

2019-10-21 10:22 UTC, katikireddy622 reviewed
sonarcloud.properties file deleted, not relevant changes to logging has been resolved and merge conflicts are resolved.

2019-10-21 22:47 UTC, munterkalmsteiner approved these changes
Looks good, thanks!

2019-11-09 10:29 UTC, closed without merging