Bugfix/[M10]-[Define this function outside of a loop]
munterkalmsteiner/inception pull request #38
Opened 2019-10-06 10:50 UTC by vineesha122

**What's in the PR**
* Define this function outside of a loop*

**How to test manually**
* ...

**Automatic testing**
* [ ] PR includes unit tests

**Documentation**
* [ ] PR updates documentation

2019-10-14 21:05 UTC, munterkalmsteiner requested changes
Hi, 
there are a couple of issues with this pull request (see comments). The one refactoring, which could be done (renderKnob.js), introduces very likely an error. Please revise.

2019-10-14 21:05 UTC, munterkalmsteiner commented on .sonarcloud.properties
> +
Sonarcloud files should be ignored.

2019-10-14 21:05 UTC, munterkalmsteiner commented on inception-html-editor/src/main/java/de/tudarmstadt/ukp/inception/htmleditor/annotatorjs/resources/annotator-full.js
> +   function ämne() {
This file contains generated code (see beginning). I think it does not make sense to refactor generated code.

2019-10-14 21:05 UTC, munterkalmsteiner commented on inception-pdf-editor/src/main/js/pdfanno/pdfjs/pdf.js
> +      var mapResolve = function(resolve) {
This file stems from 3rd party code, which is not under direct control by INCEpTION. It would make sense to submit a patch upstream, but not here.

2019-10-14 21:05 UTC, munterkalmsteiner commented on inception-pdf-editor/src/main/js/pdfanno/pdfjs/pdf.worker.js
> +
Same here, 3rd party code.

2019-10-14 21:05 UTC, munterkalmsteiner commented on inception-pdf-editor/src/main/js/pdfanno/src/core/src/render/renderKnob.js
>          good = false
I don't think this will work as expected. The new function `change()` cannot access the variable `good`. This code will fail at runtime.

2019-10-14 21:05 UTC, munterkalmsteiner commented on inception-pdf-editor/src/main/js/pdfanno/src/viewer.js
> +         function pagename(pageNum, pdfPage){
3rd party code.

2019-10-14 21:05 UTC, munterkalmsteiner commented on inception-recommendation/src/main/java/de/tudarmstadt/ukp/inception/recommendation/service/RecommendationServiceImpl.java
> +        AnnotationFS annoFS = selectSingleAt    (aCas, type, aBegin, aEnd);
This change is not related to the pull request.

2019-10-14 21:05 UTC, munterkalmsteiner commented on inception-ui-search/src/main/java/de/tudarmstadt/ukp/inception/app/ui/search/sidebar/SearchAnnotationSidebar.java
> +        AnnotationFS annoFS = selectSingleAt(aCas, type, aSearchResult.getOffsetStart(),
These changes are not related to the pull request.

2019-10-20 10:20 UTC, vineesha122 commented
The code which has to be changed is mostly present in third party code files which were not to be changed. we made changes in those files where we have to revert all the changes previously made.

so instead we are making a new pull request with the changes required.

The new pull request is"https://github.com/munterkalmsteiner/inception/pull/69"

2019-10-20 10:21 UTC, closed without merging