[M17]:<title> Tags added to respective pages.
munterkalmsteiner/inception pull request #46
Opened 2019-10-06 14:02 UTC by Yashaswini19

**What's in the PR**
Inclusions of the respective related titles to the web pages using <title> tags in the code.

2019-10-14 21:41 UTC, munterkalmsteiner requested changes
Looks good, except for some issues I commented.

2019-10-14 21:41 UTC, munterkalmsteiner commented on inception-app-webapp/.temp-inception-app-webapp - INCEpTION-classpath-arg-1570345701574.txt
> +-classpath D:\YashaswiniJulapally\inception\inception-app-webapp\target\classes;D:\YashaswiniJulapally\inception\inception-ui-core\target\classes;C:\Users\vivek\.m2\repository\de\tudarmstadt\ukp\clar
Do not submit files to the repository that are not needed.

2019-10-14 21:41 UTC, munterkalmsteiner commented on inception-imls-external/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/external/ExternalRecommenderTraitsEditor.html
> -<wicket:extend>
Why this?

2019-10-14 21:41 UTC, munterkalmsteiner commented on inception-imls-opennlp/src/main/java/de/tudarmstadt/ukp/inception/recommendation/imls/opennlp/doccat/OpenNlpDoccatRecommenderTraitsEditor.html
> -<wicket:extend>
Also here, why? This seems to be unrelated to the improvement you suggest.

2019-10-17 20:49 UTC, munterkalmsteiner requested changes
Looks good, except for the file that should not be in the repository. Please remove.

2019-10-17 20:49 UTC, munterkalmsteiner commented on inception-app-webapp/.temp-inception-app-webapp - INCEpTION-classpath-arg-1570345701574.txt
> +-classpath D:\YashaswiniJulapally\inception\inception-app-webapp\target\classes;D:\YashaswiniJulapally\inception\inception-ui-core\target\classes;C:\Users\vivek\.m2\repository\de\tudarmstadt\ukp\clar
This file still needs to be removed

2019-10-17 21:05 UTC, Yashaswini19 commented
File Removed.

2019-10-17 21:15 UTC, munterkalmsteiner approved these changes

2019-11-09 10:41 UTC, closed without merging