issue #75- [F8]: Add connection checker to external recommender settings.
munterkalmsteiner/inception pull request #76
Opened 2019-10-27 10:40 UTC by katikireddy622

**What's in the PR**

Instead of implementing a separate button for checking the external connection we have used the existing save button to verify the form validation. We have developed a custom form validator to remote URL which takes URL as an input and establishes a connection and extracts the headers from the opened connection. From the headers, we receive a status code which when equals to HTTP_OK(200), the connection is successful. If the connection is not successfully established, the form won't be saved and returns an error message with the appropriate status code.

The implementation can be seen from the screenshots below: 

![Screenshot (29)](https://user-images.githubusercontent.com/25100186/67633253-039b0600-f8ae-11e9-86f9-4b23678ad05d.png)

![Screenshot (30)](https://user-images.githubusercontent.com/25100186/67633256-21686b00-f8ae-11e9-94e8-2e6920f9587f.png)

2019-10-31 00:20 UTC, katikireddy622 commented
Please Review our pull request @munterkalmsteiner

2019-11-02 15:07 UTC, munterkalmsteiner requested changes
There are two issues with this pull request:

1. It is not based on the master branch but on one of your own previous branches. You must have 1 branch for 1 thing, not mix different concerns together.
2. On the first sight, the code works. However, when I tested it, I also got some non-existing domains to work, for example http://example.com, see screenshot:
![image](https://user-images.githubusercontent.com/720692/68072858-acec6b00-fd8a-11e9-96cb-f3c81dd69bee.png)

2019-11-02 15:07 UTC, munterkalmsteiner commented on inception-kb/src/test/java/de/tudarmstadt/ukp/inception/kb/KnowledgeBaseServiceImplQualifierIntegrationTest.java
> -    private KBHandle propertyHandle;
Deleting this leads to a compilation error

2019-11-02 16:52 UTC, katikireddy622 commented
@munterkalmsteiner  This is regarding the second issue in the pull request. [www.example.com](http://example.com) seems to be an existing domain. We have tried a non-existing domain called [www.katikireddy622.com](http://katikireddy622.com) in the first screenshot and since it does not exist it returns an error code 404. 

![Screenshot (66)](https://user-images.githubusercontent.com/25100186/68074099-d364d300-fd97-11e9-9246-380bbc295412.png)
![Screenshot (67)](https://user-images.githubusercontent.com/25100186/68074139-33f41000-fd98-11e9-96d3-bef485453f3e.png)

2019-11-03 09:12 UTC, munterkalmsteiner commented
Interesting... I get different results here:
![image](https://user-images.githubusercontent.com/720692/68082857-26836800-fe22-11e9-8ec3-915bef95625f.png)

But ok, the code regarding the check looks ok.
Your code is still based on another branch, not on the master branch. This is not good practtice. If you have time, please fix it.

2019-11-09 10:01 UTC, munterkalmsteiner commented
Overall, good effort! Changes in webanno look ok.

2019-11-09 10:01 UTC, closed without merging